[tool.poetry]
name = "mvlocscript"
version = "0.1.0"
description = ""
authors = ["nedsociety <nedsociety@gmail.com>"]

[tool.poetry.scripts]
mvloc = "mvlocscript.cli:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
lxml = "^4.9.2"
click = "^8.1.3"
json5 = "^0.9.11"
polib = "^1.1.1"
loguru = "^0.7.0"
requests = "^2.28.2"
rapidfuzz = "^2.13.7"

[tool.poetry.dev-dependencies]
pyinstaller = "^5.7"
snakeviz = "^2.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
