name: nightly

on:
  schedule:
    # 00:00 UTC every day
    - cron: '0 0 * * *' 
  workflow_dispatch:
    # Manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.FTLMV_WEBLATE_BOT_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Cache .cache directory (used for packaging)
      uses: actions/cache@v3
      with:
        path: .cache
        key: ${{ hashFiles('mvloc.config.jsonc') }}

    - name: Build packages
      run: |
        bash snippets/ci-nightly.sh ko
        bash snippets/ci-nightly.sh fr
        bash snippets/ci-nightly.sh de
        bash snippets/ci-nightly.sh zh_Hans
        bash snippets/ci-nightly.sh ru

    - name: Tag the commit
      run: |
        git config user.email "ftlmv-weblate-bot@users.noreply.github.com"
        git config user.name "ftlmv-weblate-bot"
        git tag -a nightly -m nightly -f
        git push -f origin nightly

    - name: Cleanup old releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 0
      env:
        GITHUB_TOKEN: ${{ secrets.FTLMV_WEBLATE_BOT_TOKEN }}

    - name: Release the mod
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*
        tag_name: nightly
        token: ${{ secrets.FTLMV_WEBLATE_BOT_TOKEN }}

    - name: Checkout the metadata branch
      uses: actions/checkout@v3
      with:
        ref: installer-metadata
        path: installer-metadata
        token: ${{ secrets.FTLMV_WEBLATE_BOT_TOKEN }}
    
    - name: Update the listfile
      run: |
        cd installer-metadata
        date +%s > listfile
        ls -p ../packages | grep -v / | sed "s@^@$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/latest/download/@" >> listfile
        git config user.email "ftlmv-weblate-bot@users.noreply.github.com"
        git config user.name "ftlmv-weblate-bot"
        git commit -a --amend -m "listfile update"
        git push -f origin installer-metadata

